### ISSUE TITLE
Delete of evalset does not always work

### ISSUE THREAD

**Issue by michaelwechner** [foreai-co/fore#22]
The following request

DELETE
	https://foresight.foreai.co/api/eval/set?evalset_id=evalset_20240524_120349

returns a 200, but the evalset does not get deleted

**Comment by forefab** [comment]
This evalset doesn't exist anymore. Maybe the UI didn't update? Can you check again if it still apears?

**Comment by michaelwechner** [comment]
It still does not work using the frontend, but it works when using the REST API, e.g.

DELETE https://foresight-gateway.foreai.co/api/eval/set?evalset_id=kings-and-queens

**Comment by michaelwechner** [comment]
Btw, I experience strange behaviour re browser file upload on Mac OS X, whereas I do not seem to be alone

https://cleanmymac.com/faq/why-wont-mac-upload-files

After updating and restarting Chrome, the browser file upload worked again, at least for the moment.

Let me check again whether this glitch might be connected somehow
